package controller;

public enum MenuEnum {
  EXIT, LIST_COMPANIES, LIST_COMPUTERS, CREATE_COMPUTER, READ_COMPUTER, UPDATE_COMPUTER,
  DELETE_COMPUTER, PAGED_COMPUTERS, PAGED_COMPANIES, DELETE_COMPANY;
}
